export const getNearByResturantsActionTypes={

    GET_NEAR_BY_RESTURANTS_REQUEST:"GET_NEAR_BY_RESTURANTS_REQUEST",
    GET_NEAR_BY_RESTURANTS_SUCCESS:"GET_NEAR_BY_RESTURANTS_SUCCESS",
    GET_NEAR_BY_RESTURANTS_FAILED:"GET_NEAR_BY_RESTURANTS_FAILED"
}
