export const itemDeatilsActionTypes={
    GET_ITEM_DETAILS_REQUEST:"GET_ITEM_DETAILS_REQUEST",
    GET_ITEM_DETAILS_SUCCESS:"GET_ITEM_DETAILS_SUCCESS",
    GET_ITEM_DETAILS_FAILED:"GET_ITEM_DETAILS_FAILED"
}